In [137]:
import pandas as pd
import numpy as np

In [138]:
df = pd.read_excel (r'PT DS learnerr tracker.xlsx')
df.tail()

C:\Users\happy\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Responsible,Priority,Programme,Cohort,Sponsor,Name,Surname,Email address,Disabled,Disability Support Evidence,...,Email re outcome ackowledged,Linked to Assessor on SETA system,Linked to Moderator on SETA system,Submitted for verification,Verified,Certificates received,Certificates distributed,LS / Qual,Employed/Unemployed,ID number
163,Kanyisa,NaN,Data Science,2101PT DS SP,Dimension Data,UYFZ71161110489485,QHTE42015978323417,BIZP54809593828648,NaN,False,...,NaN,False,False,False,False,False,False,NaN,NaN,NaN
164,Kanyisa,NaN,Data Science,2101PT DS SP,Dimension Data,RDHH41363913815616,NYWX03056373469070,VLAL75209002924580,NaN,False,...,NaN,False,False,False,False,False,False,NaN,NaN,NaN
165,Kanyisa,NaN,Data Science,2101PT DS SP,Dimension Data,ZUQW10719786544812,LMNN95967336502614,DNFM27329366767796,NaN,False,...,NaN,False,False,False,False,False,False,NaN,NaN,NaN
166,Kanyisa,NaN,Data Science,2101PT DS SP,Dimension Data,BSLZ67335191291894,JKFR70948244216587,GYDV10962347459130,NaN,False,...,NaN,False,False,False,False,False,False,NaN,NaN,NaN
167,Kanyisa,NaN,Data Science,2101PT DS SP,LexisNexis sponsored,IOBR21702911310571,XZIU82025395716790,IKZM29359912407744,NaN,False,...,NaN,False,False,False,False,False,False,NaN,NaN,NaN

In [139]:
# Checking how the dataframe looks like
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 58 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Responsible                                       168 non-null    object
 1   Priority                                          0 non-null      float64
 2   Programme                                         168 non-null    object
 3   Cohort                                            168 non-null    object
 4   Sponsor                                           168 non-null    object
 5   Name                                              168 non-null    object
 6   Surname                                           168 non-null    object
 7   Email address                                     168 non-null    object
 8   Disabled                                          0 non-null      float64
 9   Disability Support Evidence                       168 non-null    bool
 10  Explore member who is supporting the Disability?  24 non-null     float64
 11  SIF Completed                                     168 non-null    bool
 12  Docs checked                                      168 non-null    bool
 13  Docs in order                                     168 non-null    bool
 14  Folder created                                    168 non-null    bool
 15  SETA registered                                   168 non-null    bool
 16  St_1_ID                                           168 non-null    bool
 17  St_2_Qual                                         168 non-null    bool
 18  St_3_CV                                           168 non-null    bool
 19  St_4_Declaration of Authenticity                  168 non-null    bool
 20  st_5_Enrollment Form                              168 non-null    bool
 21  st_6_Learnership Agreement                        168 non-null    bool
 22  st_7_Copy of qualilfication being assessed        168 non-null    bool
 23  st_8_Assessment guides                            168 non-null    bool
 24  st_9_Appeals procedure                            168 non-null    bool
 25  st_10_Assessment plan                             168 non-null    bool
 26  st_11_Confirmation to be assessed                 168 non-null    bool
 27  st_12_Pre-assessment meeting                      168 non-null    bool
 28  st_13_Assessment policy                           168 non-null    bool
 29  st_14_Assessment instruments                      168 non-null    bool
 30  PoE downloaded from Athena                        168 non-null    bool
 31  PoE checked for Completeness                      168 non-null    bool
 32  PoE Complete                                      168 non-null    bool
 33  Coursework completed                              168 non-null    bool
 34  st_15_Assessment tools and answer sheet           168 non-null    bool
 35  st_18_Logbook                                     168 non-null    object
 36  st_18_Feedback Form                               168 non-null    bool
 37  st_18_Attedance Form                              168 non-null    bool
 38  Submitted for Assessment                          168 non-null    bool
 39  Workbook mark                                     0 non-null      float64
 40  Project mark                                      0 non-null      float64
 41  Summative mark                                    0 non-null      float64
 42  st_16_Assessment feedback form                    168 non-null    bool
 43  Competent / Not Yet Competent                     24 non-null     float64
 44  Assessment review document                        168 non-null    bool
 45  Email sent regarding outcome                      168 non-null    bool
 46  Assessed                                          168 non-null    bool
 47  Moderated                                         168 non-null    bool
 48  Email re outcome ackowledged                      144 non-null    float64
 49  Linked to Assessor on SETA system                 168 non-null    bool
 50  Linked to Moderator on SETA system                168 non-null    bool
 51  Submitted for verification                        168 non-null    bool
 52  Verified                                          168 non-null    bool
 53  Certificates received                             168 non-null    bool
 54  Certificates distributed                          168 non-null    bool
 55  LS / Qual                                         144 non-null    object
 56  Employed/Unemployed                               142 non-null    object
 57  ID number                                         144 non-null    object
dtypes: bool(39), float64(8), object(11)
memory usage: 31.5+ KB

In [140]:
# i use the describe() function to see the statistic distribution of the entire dataframe
df.describe()

,Priority,Disabled,Explore member who is supporting the Disability?,Workbook mark,Project mark,Summative mark,Competent / Not Yet Competent,Email re outcome ackowledged
count,0.0,0.0,24.0,0.0,0.0,0.0,24.0,144.0
mean,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
std,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
min,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
25%,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
50%,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
75%,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0
max,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0

In [141]:
# Checking the column names of the entire dataframe
for col in df.columns:
    print(col)

Responsible
Priority
Programme
Cohort
Sponsor
Name
Surname
Email address
Disabled
Disability Support Evidence
Explore member who is supporting the Disability?
SIF Completed
Docs checked
Docs in order
Folder created
SETA registered
St_1_ID
St_2_Qual
St_3_CV
St_4_Declaration of Authenticity
st_5_Enrollment Form
st_6_Learnership Agreement
st_7_Copy of qualilfication being assessed
st_8_Assessment guides
st_9_Appeals procedure
st_10_Assessment plan
st_11_Confirmation to be assessed
st_12_Pre-assessment meeting
st_13_Assessment policy
st_14_Assessment instruments
PoE downloaded from Athena
PoE checked for Completeness
PoE Complete
Coursework completed
st_15_Assessment tools and answer sheet
st_18_Logbook
st_18_Feedback Form
st_18_Attedance Form
Submitted for Assessment
Workbook mark
Project mark
Summative mark
st_16_Assessment feedback form
Competent / Not Yet Competent
Assessment review document
Email sent regarding outcome
Assessed
Moderated
Email re outcome ackowledged
Linked to Assessor on SETA system
Linked to Moderator on SETA system
Submitted for verification
Verified
Certificates received
Certificates distributed
LS / Qual
Employed/Unemployed
ID number

In [132]:
# delecting the Priority column since its contain null values
del df['Priority']

In [133]:
# Replacing the NaN values with empty cell in the following columns
df[['Unnamed: 56','Unnamed: 57','Unnamed: 58','Unnamed: 59','Unnamed: 60','Unnamed: 61','Competent / Not Yet Competent','Disabled','Workbook mark','st_16_Assessment feedback form','Assessment review document','Email re outcome ackowledged','Competent / Not Yet Competent','Docs checked']] = df[['Docs checked','Competent / Not Yet Competent','Email re outcome ackowledged','Assessment review document','st_16_Assessment feedback form','Workbook mark','Disabled','Competent / Not Yet Competent','Unnamed: 56','Unnamed: 57','Unnamed: 58','Unnamed: 59','Unnamed: 60','Unnamed: 57']].fillna('')

# Replacing the NaN values with 0 valus for this column
df[['Project mark']]=df[['Project mark']].fillna('0')

In [135]:
del df['Priority']
del df['Summative mark']

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 60 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0                                                     397 non-null    object
 1   Programme                                         390 non-null    object
 2   Cohort                                            391 non-null    object
 3   Sponsor                                           391 non-null    object
 4   Name                                              391 non-null    object
 5   Surname                                           391 non-null    object
 6   ID no                                             391 non-null    object
 7   Email address                                     391 non-null    object
 8   Disabled                                          402 non-null    object
 9   Disability Support Evidence                       391 non-null    object
 10  Explore member who is supporting the Disability?  390 non-null    object
 11  SIF Completed                                     391 non-null    float64
 12  Docs checked                                      402 non-null    object
 13  Docs in order                                     391 non-null    float64
 14  Folder created                                    391 non-null    float64
 15  SETA registered                                   391 non-null    float64
 16  St_1_ID                                           391 non-null    float64
 17  St_2_Qual                                         391 non-null    float64
 18  St_3_CV                                           391 non-null    float64
 19  St_4_Declaration of Authenticity                  391 non-null    float64
 20  st_5_Enrollment Form                              391 non-null    float64
 21  st_6_Learnership Agreement                        391 non-null    float64
 22  st_7_Copy of qualilfication being assessed        391 non-null    float64
 23  st_8_Assessment guides                            391 non-null    float64
 24  st_9_Appeals procedure                            391 non-null    float64
 25  st_10_Assessment plan                             391 non-null    float64
 26  st_11_Confirmation to be assessed                 391 non-null    float64
 27  st_12_Pre-assessment meeting                      391 non-null    float64
 28  st_13_Assessment policy                           391 non-null    float64
 29  st_14_Assessment instruments                      391 non-null    float64
 30  PoE downloaded from Athena                        391 non-null    float64
 31  PoE checked for Completeness                      391 non-null    float64
 32  PoE Complete                                      391 non-null    float64
 33  Coursework completed                              391 non-null    float64
 34  st_15_Assessment tools and answer sheet           391 non-null    float64
 35  st_18_Logbook                                     391 non-null    float64
 36  st_18_Feedback Form                               391 non-null    float64
 37  st_18_Attedance Form                              391 non-null    float64
 38  Submitted for Assessment                          391 non-null    float64
 39  Workbook mark                                     402 non-null    object
 40  Project mark                                      402 non-null    object
 41  st_16_Assessment feedback form                    402 non-null    object
 42  Assessment review document                        402 non-null    object
 43  Email sent regarding outcome                      391 non-null    float64
 44  Email re outcome ackowledged                      402 non-null    object
 45  Linked to Assessor on SETA system                 391 non-null    float64
 46  Assessed                                          391 non-null    float64
 47  Competent / Not Yet Competent                     402 non-null    object
 48  Linked to Moderator on SETA system                391 non-null    float64
 49  Moderated                                         391 non-null    float64
 50  Submitted for verification                        391 non-null    float64
 51  Verified                                          391 non-null    float64
 52  Certificates received                             391 non-null    float64
 53  Certificates distributed                          391 non-null    float64
 54  Unnamed: 56                                       402 non-null    object
 55  Unnamed: 57                                       402 non-null    object
 56  Unnamed: 58                                       402 non-null    object
 57  Unnamed: 59                                       402 non-null    object
 58  Unnamed: 60                                       402 non-null    object
 59  Unnamed: 61                                       402 non-null    object
dtypes: float64(36), object(24)
memory usage: 188.6+ KB